services:
  db:
    image: postgres:15-alpine
    container_name: banco-prod
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=transacoes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # O SERVIÇO 'api' DEVE ESTAR NO MESMO NÍVEL DE 'db'
  api:
    build: .
    container_name: api-v1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/transacoes_db

# ESTE BLOCO DEVE ESTAR NO NÍVEL ZERO
volumes:
  postgres_data: